-- Migration 005: English vocabulary words by class.
-- Run against arina_db after base schema migrations.

CREATE SCHEMA IF NOT EXISTS arina;

CREATE TABLE IF NOT EXISTS arina.english_vocabulary_words (
    id SERIAL PRIMARY KEY,
    class_number INTEGER NOT NULL,
    english_word VARCHAR(160) NOT NULL,
    russian_translation VARCHAR(200) NOT NULL,
    transcription VARCHAR(200),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT english_vocabulary_words_class_number_word_key UNIQUE (class_number, english_word, russian_translation)
);

CREATE INDEX IF NOT EXISTS idx_english_vocabulary_words_class_number
ON arina.english_vocabulary_words(class_number);

INSERT INTO arina.english_vocabulary_words (class_number, english_word, russian_translation, transcription)
VALUES
    (2, 'Sheep', 'Овца', '[ʃiːp]'),
    (2, 'Fish', 'Рыба', '[fɪʃ]'),
    (2, 'Ship', 'Корабль', '[ʃɪp]'),
    (2, 'Chick', 'Цыплёнок', '[tʃɪk]'),
    (2, 'Cheese', 'Сыр', '[tʃiːz]'),
    (2, 'Thumb', 'Большой палец', '[θʌm]'),
    (2, 'Photo', 'Фотография', '[''fəʊtəʊ]'),
    (2, 'Dolphin', 'Дельфин', '[''dɒlfɪn]'),
    (2, 'Elephant', 'Слон', '[''elɪfənt]'),
    (2, 'Brother', 'Брат', '[''brʌðə(r)]'),
    (2, 'Sister', 'Сестра', '[''sɪstə(r)]'),
    (2, 'He', 'Он', '[hiː]'),
    (2, 'She', 'Она', '[ʃiː]'),
    (2, 'Stand up', 'Встать', '[stænd ʌp]'),
    (2, 'Sit down', 'Сесть', '[sɪt daʊn]'),
    (2, 'Open your books', 'Откройте книги', '[''əʊpən jɔː(r) bʊks]'),
    (2, 'Close your books', 'Закройте книги', '[kləʊz jɔː(r) bʊks]'),
    (2, 'This is', 'Это', '[ðɪs ɪz]'),
    (2, 'School', 'Школа', '[skuːl]'),
    (2, 'Pen', 'Ручка', '[pen]'),
    (2, 'Book', 'Книга', '[bʊk]'),
    (2, 'Pencil', 'Карандаш', '[''pensl]'),
    (2, 'Workbook', 'Рабочая тетрадь', '[''wɜːkbʊk]'),
    (2, 'Family', 'Семья', '[''fæməli]'),
    (2, 'My', 'Мой', '[maɪ]'),
    (2, 'Daddy', 'Папа', '[''dædi]'),
    (2, 'Father', 'Папа', '[''fɑːðə(r)]'),
    (2, 'Mammy', 'Мама', '[''mæmi]'),
    (2, 'Mother', 'Мама', '[''mʌðə(r)]'),
    (2, 'Grandpa', 'Дедушка', '[''ɡrænpɑː]'),
    (2, 'Grandma', 'Бабушка', '[''ɡrænmɑː]'),
    (2, 'Red', 'Красный', '[red]'),
    (2, 'Colour', 'Цвет', '[''kʌlə(r)]'),
    (2, 'Yellow', 'Жёлтый', '[''jeləʊ]'),
    (2, 'Green', 'Зелёный', '[ɡriːn]'),
    (2, 'White', 'Белый', '[waɪt]'),
    (2, 'Blue', 'Синий', '[bluː]'),
    (2, 'Home', 'Дом', '[həʊm]'),
    (2, 'House', 'Дом', '[haʊs]'),
    (2, 'Chair', 'Стул', '[tʃeə(r)]'),
    (2, 'Table', 'Стол', '[''teɪbl]'),
    (2, 'Black', 'Чёрный', '[blæk]'),
    (2, 'Brown', 'Коричневый', '[braʊn]'),
    (2, 'Garden', 'Сад', '[''ɡɑːdn]'),
    (2, 'Kitchen', 'Кухня', '[''kɪtʃɪn]'),
    (2, 'Bedroom', 'Спальня', '[''bedruːm]'),
    (2, 'Living room', 'Гостиная', '[''lɪvɪŋ ruːm]'),
    (2, 'Bathroom', 'Ванная комната', '[''bɑːθruːm]'),
    (2, 'Door', 'Дверь', '[dɔː(r)]'),
    (2, 'Floor', 'Пол', '[flɔː(r)]'),
    (2, 'Happy', 'Счастливый', '[''hæpi]'),
    (2, 'Sad', 'Грустный', '[sæd]'),
    (2, 'Birthday', 'День рождения', '[''bɜːθdeɪ]'),
    (2, 'One', 'Один', '[wʌn]'),
    (2, 'Two', 'Два', '[tuː]'),
    (2, 'Three', 'Три', '[θriː]'),
    (2, 'Four', 'Четыре', '[fɔː(r)]'),
    (2, 'Five', 'Пять', '[faɪv]'),
    (2, 'Six', 'Шесть', '[sɪks]'),
    (2, 'Seven', 'Семь', '[''sevn]'),
    (2, 'Eight', 'Восемь', '[eɪt]'),
    (2, 'Nine', 'Девять', '[naɪn]'),
    (2, 'Ten', 'Десять', '[ten]'),
    (2, 'Food', 'Еда', '[fuːd]'),
    (2, 'Apple', 'Яблоко', '[''æpl]'),
    (2, 'Milk', 'Молоко', '[mɪlk]'),
    (2, 'Toy', 'Игрушка', '[tɔɪ]'),
    (2, 'Nose', 'Нос', '[nəʊz]'),
    (2, 'Mouth', 'Рот', '[maʊθ]'),
    (2, 'Eyes', 'Глаза', '[aɪz]'),
    (2, 'Ears', 'Уши', '[ɪəz]'),

    (3, 'Holiday', 'Каникулы', '[''hɒlədeɪ]'),
    (3, 'It is windy', 'Ветрено', '[ɪt ɪz ''wɪndi]'),
    (3, 'It is cold', 'Холодно', '[ɪt ɪz kəʊld]'),
    (3, 'Winter', 'Зима', '[''wɪntə(r)]'),
    (3, 'Autumn', 'Осень', '[''ɔːtəm]'),
    (3, 'Summer', 'Лето', '[''sʌmə(r)]'),
    (3, 'Spring', 'Весна', '[sprɪŋ]'),
    (3, 'Socks', 'Носки', '[sɒks]'),
    (3, 'T-shirt', 'Футболка', '[''tiː ʃɜːt]'),
    (3, 'Shoes', 'Туфли', '[ʃuːz]'),
    (3, 'Skirt', 'Юбка', '[skɜːt]'),
    (3, 'School', 'Школа', '[skuːl]'),
    (3, 'School bag', 'Портфель', '[skuːl bæɡ]'),
    (3, 'Rubber', 'Ластик', '[''rʌbə(r)]'),
    (3, 'Ruler', 'Линейка', '[''ruːlə(r)]'),
    (3, 'Pencil case', 'Пенал', '[''pensl keɪs]'),
    (3, 'Thirteen', 'Тринадцать', '[ˌθɜː''tiːn]'),
    (3, 'Fourteen', 'Четырнадцать', '[ˌfɔː''tiːn]'),
    (3, 'Fifteen', 'Пятнадцать', '[ˌfɪf''tiːn]'),
    (3, 'Sixteen', 'Шестнадцать', '[ˌsɪks''tiːn]'),
    (3, 'Seventeen', 'Семнадцать', '[ˌsev''ntiːn]'),
    (3, 'Eighteen', 'Восемнадцать', '[ˌeɪ''tiːn]'),
    (3, 'Nineteen', 'Девятнадцать', '[ˌnaɪn''tiːn]'),
    (3, 'Twenty', 'Двадцать', '[''twenti]'),
    (3, 'English', 'Английский язык', '[''ɪŋɡlɪʃ]'),
    (3, 'Maths', 'Математика', '[mæθs]'),
    (3, 'Geography', 'География', '[dʒi''ɒɡrəfi]'),
    (3, 'PE', 'Физкультура', '[ˌpiː ''iː]'),
    (3, 'History', 'История', '[''hɪstri]'),
    (3, 'Science', 'Естествознание', '[''saɪəns]'),
    (3, 'Art', 'Изобразительное искусство', '[ɑːt]'),
    (3, 'Music', 'Музыка', '[''mjuːzɪk]'),
    (3, 'I', 'Я', '[aɪ]'),
    (3, 'You', 'Ты', '[juː]'),
    (3, 'He', 'Он', '[hiː]'),
    (3, 'She', 'Она', '[ʃiː]'),
    (3, 'We', 'Мы', '[wiː]'),
    (3, 'They', 'Они', '[ðeɪ]'),
    (3, 'Chicken', 'Курица', '[''tʃɪkɪn]'),
    (3, 'Egg', 'Яйцо', '[eɡ]'),
    (3, 'Water', 'Вода', '[''wɔːtə(r)]'),
    (3, 'Meat', 'Мясо', '[miːt]'),
    (3, 'Potato', 'Картофель', '[pə''teɪtəʊ]'),
    (3, 'Carrot', 'Морковь', '[''kærət]'),
    (3, 'Rice', 'Рис', '[raɪs]'),
    (3, 'Ball', 'Мяч', '[bɔːl]'),
    (3, 'Doll', 'Кукла', '[dɒl]'),
    (3, 'Train', 'Поезд', '[treɪn]')
ON CONFLICT (class_number, english_word, russian_translation) DO UPDATE
SET transcription = EXCLUDED.transcription,
    is_active = TRUE;
